<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BH.UI.Civil.Engine</RootNamespace>
    <OutputPath>..\Build\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AssemblyTitle>Engine_Civil_UI</AssemblyTitle>
    <Description>https://github.com/BHoM/Civil3D_Toolkit</Description>
    <Product>Engine_Civil_UI</Product>
    <Copyright>Copyright © https://github.com/BHoM</Copyright>
    <AssemblyVersion>5.0.0.0</AssemblyVersion>
    <FileVersion>5.3.0.0</FileVersion>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;C:\ProgramData\BHoM\Assemblies&quot; /Y" />
  </Target>
  <ItemGroup>
     <Reference Include="accoremgd">
      <HintPath>..\libs\accoremgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acdbmgd">
      <HintPath>..\libs\acdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acmgd">
      <HintPath>..\libs\acmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AecBaseMgd">
      <HintPath>..\libs\AecBaseMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AeccDbMgd">
      <HintPath>..\libs\AeccDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BHoM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BHoM_Engine">
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Dimensional_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Dimensional_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Geometry_Engine">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Geometry_Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Geometry_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Geometry_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Query\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Civil3D_oM\Civil3D_oM.csproj" />
  </ItemGroup>
</Project>
