<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BH.UI.Civil</RootNamespace>
    <OutputPath>..\Build\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AssemblyTitle>Civil_UI</AssemblyTitle>
    <Description>https://github.com/BHoM/Civil3D_Toolkit</Description>
    <Product>Civil_UI</Product>
    <Copyright>Copyright © https://github.com/BHoM</Copyright>
    <AssemblyVersion>5.0.0.0</AssemblyVersion>
    <FileVersion>5.3.0.0</FileVersion>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="RD /S /Q &quot;C:\Users\$(Username)\AppData\Roaming\Autodesk\ApplicationPlugins\BHoM.bundle&quot;&#xD;&#xA;xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;C:\ProgramData\BHoM\Assemblies&quot; /Y&#xD;&#xA;C:\Windows\System32\xcopy &quot;$(ProjectDir)PluginFile\PackageContents.xml&quot; &quot;C:\Users\$(Username)\AppData\Roaming\Autodesk\ApplicationPlugins\BHoM.bundle\&quot;" />
  </Target>
  <ItemGroup>
    <Reference Include="Adapter_Engine">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Adapter_Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Adapter_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Adapter_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BHoM">
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_Adapter">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM_Adapter.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="BHoM_Engine">
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Data_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Data_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Serialiser_Engine">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Serialiser_Engine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Socket_Adapter">
      <HintPath>C:\ProgramData\BHoM\Assemblies\Socket_Adapter.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Socket_oM">
      <HintPath>C:\ProgramData\BHoM\Assemblies\Socket_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Adapter_Civil_UI\Adapter_Civil_UI.csproj" />
    <ProjectReference Include="..\Civil3D_Adapter\Civil3D_Adapter.csproj" />
    <ProjectReference Include="..\Civil3D_Engine\Civil3D_Engine.csproj" />
    <ProjectReference Include="..\Civil3D_oM\Civil3D_oM.csproj" />
    <ProjectReference Include="..\Engine_Civil_UI\Engine_Civil_UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="PluginFile\PackageContents.xml" />
  </ItemGroup>
</Project>
