<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BH.UI.Civil.Adapter</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <OutputPath>..\Build\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;C:\ProgramData\BHoM\Assemblies&quot; /Y" />
  </Target>
  <ItemGroup>
    <Reference Include="accoremgd">
      <HintPath>..\libs\accoremgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acdbmgd">
      <HintPath>..\libs\acdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acmgd">
      <HintPath>..\libs\acmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AecBaseMgd">
      <HintPath>..\libs\AecBaseMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="AeccDbMgd">
      <HintPath>..\libs\AeccDbMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Adapter_Engine">
      <HintPath>C:\ProgramData\BHoM\Assemblies\Adapter_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Adapter_oM">
      <HintPath>C:\ProgramData\BHoM\Assemblies\Adapter_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM">
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_Adapter">
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM_Adapter.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Geometry_Engine">
      <HintPath>C:\ProgramData\BHoM\Assemblies\Geometry_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Geometry_oM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\Geometry_oM.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Civil3D_Engine\Civil3D_Engine.csproj" />
    <ProjectReference Include="..\Civil3D_oM\Civil3D_oM.csproj" />
    <ProjectReference Include="..\Engine_Civil_UI\Engine_Civil_UI.csproj" />
  </ItemGroup>
</Project>
