<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
<TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>BH.Engine.Adapters.Civil3D</RootNamespace>
    <OutputPath>..\Build\</OutputPath>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
    <AssemblyTitle>Civil3D_Engine</AssemblyTitle>
    <Description>https://github.com/BHoM/Civil3D_Toolkit</Description>
    <Product>Civil3D_Engine</Product>
    <Copyright>Copyright © https://github.com/BHoM</Copyright>
    <AssemblyVersion>9.0.0.0</AssemblyVersion>
    <FileVersion>9.1.0.0</FileVersion>
  </PropertyGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(TargetDir)$(TargetFileName)&quot;  &quot;C:\ProgramData\BHoM\Assemblies&quot; /Y" />
  </Target>
  <ItemGroup>
    <Reference Include="BHoM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="BHoM_Engine">
      <HintPath>$(ProgramData)\BHoM\Assemblies\BHoM_Engine.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <Reference Include="Dimensional_oM">
      <HintPath>$(ProgramData)\BHoM\Assemblies\Dimensional_oM.dll</HintPath>
      <Private>False</Private>
      <SpecificVersion>False</SpecificVersion>
    </Reference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Civil3D_oM\Civil3D_oM.csproj" />
  </ItemGroup>
</Project>
